table dim_geography
	lineageTag: 787e28b2-19af-4ad7-8136-81c4b51b1fd4

	column id
		dataType: int64
		formatString: 0
		lineageTag: 1cd45c35-35db-4b4c-bc5f-9086d1eb5782
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 073deffe-6d5f-4872-a099-28ac17413a47
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 58b4ca1c-58a9-4322-967b-6ac86f6b729e
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	partition dim_geography = m
		mode: import
		source =
				let
				    Source = clean_data,
				    #"C:\Users\usuario\Desktop\marketinganalyticsportfolio\clean_data\_geography csv" = Source{[#"Folder Path"="C:\Users\usuario\Desktop\marketinganalyticsportfolio\clean_data\",Name="geography.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\Users\usuario\Desktop\marketinganalyticsportfolio\clean_data\_geography csv",[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"country", type text}, {"city", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

