table dim_customers
	lineageTag: ee175171-c0da-4549-8167-8e6e53b42906

	column id
		dataType: int64
		formatString: 0
		lineageTag: fad30c29-8c83-4f5c-878c-5f21c1693701
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: b84ce167-cd3c-42b2-8c46-f5590c2bab30
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: f1950ac3-df03-457a-adec-9e81768a9b29
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 51c99c75-1202-4b4d-a07b-53061ae06f46
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column age
		dataType: int64
		formatString: 0
		lineageTag: 3a799046-b9d0-46d1-b3f6-a01ae1bfc8c8
		summarizeBy: sum
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column geography_id
		dataType: int64
		formatString: 0
		lineageTag: fe2b4c01-bcf3-4b1f-bb20-1847e8c01ffc
		summarizeBy: none
		sourceColumn: geography_id

		annotation SummarizationSetBy = Automatic

	partition dim_customers = m
		mode: import
		source =
				let
				    Source = clean_data,
				    #"C:\Users\usuario\Desktop\marketinganalyticsportfolio\clean_data\_customers csv" = Source{[#"Folder Path"="C:\Users\usuario\Desktop\marketinganalyticsportfolio\clean_data\",Name="customers.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\Users\usuario\Desktop\marketinganalyticsportfolio\clean_data\_customers csv",[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"name", type text}, {"email", type text}, {"gender", type text}, {"age", Int64.Type}, {"geography_id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

